version: "2"
run:
  go: "1.26"
linters:
  enable:
    - gocritic
    - gocyclo
  disable:
    - exhaustive
    - godot
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
