# GoReleaser configuration for check-image
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: check-image
    main: ./cmd/check-image
    binary: check-image

    ldflags:
      - -s -w
      - -X github.com/jarfernandez/check-image/internal/version.Version=v{{.Version}}
      - -X github.com/jarfernandez/check-image/internal/version.Commit={{.ShortCommit}}
      - -X github.com/jarfernandez/check-image/internal/version.BuildDate={{.Date}}

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Windows ARM64 is not commonly used
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      check-image_{{.Version}}_{{.Os}}_{{.Arch}}

    format_overrides:
      - goos: windows
        formats: [zip]

    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - config/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  disable: true

release:
  github:
    owner: jarfernandez
    name: check-image
  draft: false
  prerelease: auto
  mode: append

brews:
  - name: check-image
    repository:
      owner: jarfernandez
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    directory: Formula

    homepage: "https://github.com/jarfernandez/check-image"
    description: "Validate container images against security and operational standards"
    license: "MIT"

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "Brew formula update for check-image version {{ .Tag }}"

    skip_upload: auto

    test: |
      system "#{bin}/check-image", "version", "--short"
